{{- if .Values.servicemonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.name | quote }}
  labels:
    prometheus: k8s
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      targetPort: 9187
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: {{ .Values.name | quote }}
{{- end }}
